channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.6.9
  - pandas==0.25.0
  - nodejs
  - graphviz
  - pip
  - pip:
    - matplotlib
    - seaborn
    - sklearn
    - numpy
    - tensorflow
    - jupyter-tensorboard
    - pydot
    - graphviz
    - jupyter-server-proxy
